import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-300">
        <Nav></Nav>
        <div className="m-3">{children}</div>
      </body>
    </html>
  );
}
